        self.check_button_1 = customtkinter.CTkCheckBox(self.third_task_frame, text='1')
        self.check_button_1.grid(row=1, column=0, ipadx=60, padx=10, pady=10)
        self.check_button_2 = customtkinter.CTkCheckBox(self.third_task_frame, text='2')
        self.check_button_2.grid(row=2, column=0, ipadx=60, padx=10, pady=10)
        self.check_button_3 = customtkinter.CTkCheckBox(self.third_task_frame, text='4')
        self.check_button_3.grid(row=3, column=0, ipadx=60, padx=10, pady=10)
        self.check_button_4 = customtkinter.CTkCheckBox(self.third_task_frame, text='8')
        self.check_button_4.grid(row=3, column=0, ipadx=60, padx=10, pady=10)
        self.check_button_5 = customtkinter.CTkCheckBox(self.third_task_frame, text='16')
        self.check_button_5.grid(row=4, column=0, ipadx=60, padx=10, pady=10)